# Generated by Django 2.2.1 on 2019-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JusfiticativaBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indisponibilidade', models.BooleanField(choices=[(True, 'Sim'), (False, 'Nao')])),
                ('codigo_justificativa', models.IntegerField()),
                ('jusfiticativa', models.CharField(max_length=50)),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('modelo_atrelado', models.CharField(choices=[('CANCELAMENTO', 'Cancelamento'), ('CONTA_POR_GRADE', 'Conta por grade'), ('CRITICAS', 'Críticas'), ('DEVOLUCAO', 'Devolução'), ('DIVERGENCIA_DE_PRECO', 'Divergência de preço'), ('FALTA_DE_PRODUTO', 'Falta de produto'), ('FURO', 'Furo'), ('OUTROS', 'Outros'), ('PEDIDOS_ORFAOS', 'Pedidos órfãos'), ('REPROGRAMACAO_POR_ATRASO_DE_CARREGAMENTO', 'Reprogramação por atraso de carregamento'), ('REPROGRAMACAO_DE_PRODUTO_NO_MOMENTO_DO_CARREGAMENTO', 'Reprogramação de produto no momento do carregamento')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JusfiticativaCa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indisponibilidade', models.BooleanField(choices=[(True, 'Sim'), (False, 'Nao')])),
                ('codigo_justificativa', models.IntegerField()),
                ('jusfiticativa', models.CharField(max_length=50)),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('modelo_atrelado', models.CharField(choices=[('CANCELAMENTO', 'Cancelamento'), ('CONTA_POR_GRADE', 'Conta por grade'), ('CRITICAS', 'Críticas'), ('DEVOLUCAO', 'Devolução'), ('DIVERGENCIA_DE_PRECO', 'Divergência de preço'), ('FALTA_DE_PRODUTO', 'Falta de produto'), ('FURO', 'Furo'), ('OUTROS', 'Outros'), ('PEDIDOS_ORFAOS', 'Pedidos órfãos'), ('REPROGRAMACAO_POR_ATRASO_DE_CARREGAMENTO', 'Reprogramação por atraso de carregamento'), ('REPROGRAMACAO_DE_PRODUTO_NO_MOMENTO_DO_CARREGAMENTO', 'Reprogramação de produto no momento do carregamento')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogProcessoBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('CANCELADO', 'Cancelado'), ('EXECUCAO', 'Em execução'), ('ERRO', 'ERRO'), ('FINALIZADO', 'Finalizado')], default='TODOS', max_length=50)),
                ('mensagem', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosSNSRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('rule', models.CharField(choices=[('RATEIO', 'Rateio'), ('VOLTA_DA_PERNA', 'Volta da Perna'), ('ALOCACAO_NORMAL', 'Alocação Normal / Malha Compartilhada'), ('MTO', 'MTO')], max_length=500)),
                ('value', models.IntegerField(default=0, null=True)),
                ('data_insert', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaidaSns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sequencial', models.IntegerField()),
                ('cod_unidade', models.IntegerField()),
                ('nome_unidade', models.CharField(max_length=256)),
                ('cod_unidade_original', models.IntegerField()),
                ('regional', models.CharField(max_length=256)),
                ('cod_cliente', models.IntegerField()),
                ('nome_cliente', models.CharField(max_length=256)),
                ('geografia', models.CharField(max_length=256)),
                ('categoria', models.CharField(max_length=256)),
                ('embalagem_fechada', models.CharField(max_length=256)),
                ('embalagem_aberta', models.CharField(max_length=256)),
                ('cod_produto', models.IntegerField()),
                ('nome_produto', models.CharField(max_length=256)),
                ('data_puxada', models.DateField()),
                ('marcacao', models.CharField(max_length=256)),
                ('ns_gross', models.IntegerField()),
                ('status_item', models.CharField(max_length=256)),
                ('motivo', models.CharField(max_length=256)),
                ('num_carro', models.IntegerField()),
                ('cod_justificativa', models.IntegerField()),
                ('justificativa', models.CharField(max_length=256)),
                ('cod_justificativa_bo', models.IntegerField()),
                ('justificativa_bo', models.CharField(max_length=256)),
                ('canal_marcacao', models.CharField(max_length=256)),
                ('entrada', models.CharField(max_length=256)),
                ('liquid_type', models.CharField(choices=[('TODOS', 'Todos'), ('CERVEJA', 'Cerveja'), ('REFRIGENANC', 'Refrigerante')], default='TODOS', max_length=12)),
                ('input_type', models.CharField(choices=[('ADHOC', 'AdHoc'), ('CDD', 'CDD'), ('REVENDA', 'Revenda'), ('FOTO', 'Foto'), ('CUBO', 'Cubo'), ('DE_PARA_GEO', 'De Para GEO')], default='ADHOC', max_length=12)),
                ('channel_type', models.CharField(choices=[('ASVD', 'ASVD'), ('ASCD', 'ASCD'), ('REVENDA', 'Revenda'), ('ROTA', 'Rota')], default='ROTA', max_length=7)),
            ],
        ),
    ]
