# Generated by Django 2.2.1 on 2019-08-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('cod_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_motivo', models.CharField(max_length=100)),
                ('ind_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='canal_marcacao',
            new_name='canal',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='cod_sequencial',
            new_name='cod_cliente_orig',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='cod_unidade',
            new_name='cod_fab',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='data_puxada',
            new_name='dat_original',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='categoria',
            new_name='dsc_geo',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='geografia',
            new_name='dsc_justificativa',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='justificativa',
            new_name='dsc_justificativa_bo',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='justificativa_bo',
            new_name='dsc_motivo',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='motivo',
            new_name='dsc_regional',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='nome_cliente',
            new_name='nom_abr_unb',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='nome_produto',
            new_name='nom_abrev_prod',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='nome_unidade',
            new_name='nom_fantasia_cliente',
        ),
        migrations.RenameField(
            model_name='saidasns',
            old_name='regional',
            new_name='sgl_status_item',
        ),
        migrations.RemoveField(
            model_name='jusfiticativaca',
            name='codigo_justificativa',
        ),
        migrations.RemoveField(
            model_name='jusfiticativaca',
            name='indisponibilidade',
        ),
        migrations.RemoveField(
            model_name='jusfiticativaca',
            name='jusfiticativa',
        ),
        migrations.RemoveField(
            model_name='jusfiticativaca',
            name='modelo_atrelado',
        ),
        migrations.RemoveField(
            model_name='saidasns',
            name='channel_type',
        ),
        migrations.RemoveField(
            model_name='saidasns',
            name='cod_unidade_original',
        ),
        migrations.RemoveField(
            model_name='saidasns',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='saidasns',
            name='liquid_type',
        ),
        migrations.RemoveField(
            model_name='saidasns',
            name='status_item',
        ),
        migrations.AddField(
            model_name='jusfiticativaca',
            name='cod_justificativa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jusfiticativaca',
            name='cod_tipo_justificativa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jusfiticativaca',
            name='dsc_justificativa',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jusfiticativaca',
            name='ind_automatica',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Nao')], default=False),
        ),
        migrations.AddField(
            model_name='jusfiticativaca',
            name='ind_cancelamento',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Nao')], default=False),
        ),
        migrations.AddField(
            model_name='jusfiticativaca',
            name='val_flag_indisp',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Nao')], default=False),
        ),
        migrations.AddField(
            model_name='saidasns',
            name='business_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saidasns',
            name='liquido',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('CERVEJA', 'Cerveja'), ('REFRIGENANC', 'Refrigerante')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='jusfiticativaca',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametrossnsrule',
            name='rule',
            field=models.CharField(choices=[('rateio', 'Rateio'), ('volta_perna', 'Volta da Perna'), ('alocacao_normal', 'Alocação Normal / Malha Compartilhada'), ('mto', 'MTO')], max_length=500),
        ),
    ]
