# Generated by Django 2.2.1 on 2019-08-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20190815_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='jusfiticativaca',
            name='cod_motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sns.Motivos'),
        ),
    ]
