# Generated by Django 2.2.1 on 2019-08-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_jusfiticativaca_cod_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jusfiticativaca',
            name='cod_justificativa',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
