# Generated by Django 2.2.1 on 2019-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumolog',
            name='importacao_ok',
        ),
        migrations.AlterField(
            model_name='insumorastreabilidade',
            name='cod_cliente',
            field=models.FloatField(null=True),
        ),
    ]
