# Generated by Django 2.2.1 on 2019-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_auto_20190813_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumopromax',
            name='cod_unidade',
            field=models.FloatField(null=True),
        ),
    ]
