# Generated by Django 2.2.1 on 2019-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_auto_20190813_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumorastreabilidade',
            name='cod_produto',
            field=models.FloatField(null=True),
        ),
    ]
