# Generated by Django 2.2.1 on 2019-08-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0004_auto_20190813_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoconsolidado',
            name='cod_cliente',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='insumoconsolidado',
            name='codpro',
            field=models.FloatField(null=True),
        ),
    ]
