# Generated by Django 2.2.1 on 2019-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0006_auto_20190813_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoconsolidado',
            name='cod_cliente',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
