# Generated by Django 2.2.1 on 2019-08-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0007_auto_20190813_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumopromax',
            name='cod_unidade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insumorastreabilidade',
            name='cod_cliente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insumorastreabilidade',
            name='cod_produto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
