# Generated by Django 2.2.1 on 2019-08-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0008_auto_20190813_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoconsolidado',
            name='codcom',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insumoconsolidado',
            name='coddir',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insumoconsolidado',
            name='codfab',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insumoconsolidado',
            name='codpro',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insumopromax',
            name='cod_unidade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='insumorastreabilidade',
            name='cod_cliente',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='insumorastreabilidade',
            name='cod_produto',
            field=models.FloatField(null=True),
        ),
    ]
