# Generated by Django 2.2.1 on 2019-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0009_auto_20190813_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumorastreabilidade',
            name='val_qtd_prod_hl',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='insumorastreabilidade',
            name='val_qtd_prod_sku',
            field=models.FloatField(null=True),
        ),
    ]
