# Generated by Django 2.2.1 on 2019-10-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0011_insumofoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoADHOCCUBO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_unidade', models.IntegerField(blank=True, null=True)),
                ('nomeunidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_unidade_original', models.IntegerField(blank=True, null=True)),
                ('regional', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_cliente', models.IntegerField(blank=True, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('geografia', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('embalagem_fechada', models.CharField(blank=True, max_length=50, null=True)),
                ('embalagem_aberta', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_prod', models.IntegerField(blank=True, null=True)),
                ('nome_prod', models.CharField(blank=True, max_length=50, null=True)),
                ('data_puxada', models.CharField(blank=True, max_length=50, null=True)),
                ('marcacao', models.CharField(blank=True, max_length=50, null=True)),
                ('entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('ns_gross', models.CharField(blank=True, max_length=50, null=True)),
                ('ns_net', models.CharField(blank=True, max_length=50, null=True)),
                ('status_Item', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('num_carro', models.IntegerField(blank=True, null=True)),
                ('cod_justificativa', models.IntegerField(blank=True, null=True)),
                ('justificativa', models.IntegerField(blank=True, null=True)),
                ('cod_justificativa_bo', models.IntegerField(blank=True, null=True)),
                ('justificativa_bo', models.CharField(blank=True, max_length=100, null=True)),
                ('canal_de_marcacao', models.CharField(blank=True, max_length=50, null=True)),
                ('micro_regiao', models.CharField(blank=True, max_length=50, null=True)),
                ('abci', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_venda', models.CharField(blank=True, max_length=50, null=True)),
                ('entrada', models.CharField(blank=True, max_length=50, null=True)),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.InsumoLog')),
            ],
        ),
        migrations.DeleteModel(
            name='InsumoFoto',
        ),
    ]
